# -*- coding: utf-8 -*-
"""resume_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuZRS644tKPccphpoOrvWMMrSW27uJAA
"""

import streamlit as st
import pickle
from sklearn.metrics.pairwise import cosine_similarity
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import nltk

# Download NLTK resources
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

# Load TF-IDF vectorizer
with open("tfidf_vectorizer.pkl", "rb") as f:
    vectorizer = pickle.load(f)

# Text cleaning function
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\S+@\S+', ' ', text)
    text = re.sub(r'\d+', ' ', text)
    text = re.sub(r'[^a-z\s]', ' ', text)
    tokens = text.split()
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)

st.title("📄 Resume Matching System")

job_description = st.text_area("Enter Job Description:")

uploaded_files = st.file_uploader("Upload Resumes (.txt)", accept_multiple_files=True)

if st.button("Match Resumes"):
    if not job_description or not uploaded_files:
        st.warning("Please enter job description and upload resumes!")
    else:
        resumes = []
        resume_names = []
        for uploaded_file in uploaded_files:
            text = uploaded_file.read().decode("utf-8")
            resumes.append(clean_text(text))
            resume_names.append(uploaded_file.name)

        # TF-IDF transform
        tfidf_resumes = vectorizer.transform(resumes)
        tfidf_job = vectorizer.transform([clean_text(job_description)])

        # Cosine similarity
        similarity_scores = cosine_similarity(tfidf_job, tfidf_resumes).flatten()

        # Ranking
        ranked_indices = similarity_scores.argsort()[::-1]

        st.subheader("✅ Resume Ranking:")
        for idx in ranked_indices:
            st.write(f"{resume_names[idx]} → Score: {similarity_scores[idx]:.3f}")

